name: ESP32 Arduino Solo1

on:
  push:
    branches:
    - release/v3.3-solo1
  pull_request:

jobs:

  build-libs:
    name: Build Arduino Libs
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt install git wget curl libssl-dev libncurses-dev flex bison gperf python python-pip python-setuptools python-serial python-click python-cryptography python-future python-pyparsing python-pyelftools cmake ninja-build ccache
    - name: Install Python Wheel
      run: pip install wheel
    - name: Build Arduino Libs
      run: bash ./build.sh
    - name: Upload archive
      uses: actions/upload-artifact@v1
      with:
        name: esp32-arduino
        path: dist
    - name: Delete all files and folders
      run: |
        rm -rf *
        git config --local user.name "esp32-arduino-lib-builder"
        git checkout framework-arduinoespressif32
    - name: Display files from branch ckeckout
      run: ls -R
    - uses: actions/download-artifact@v2
      with:
        name: esp32-arduino
        path: ./esp32-arduino
    - name: Display downloaded files
      run: ls -R
      working-directory: ./esp32-arduino       
    - name: Commit files  # transfer the builded files into the repository
      run: |
        cd esp32-arduino
        cp -Rf ./* ../
        cd ..
        rm -rf esp32-arduino
        git rm -r --cached .
        git add -f *.*
        git commit -m "esp32-arduino-lib v3.3-solo1"
    - name: Push changes  # push the files to branch framework-arduinoespressif32
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: 'framework-arduinoespressif32'
        force: true
